### ISSUE TITLE
DNAWeb not updating web page after changes are made and saved in .scss

### ISSUE THREAD

**Issue by D-code-er** [angelsix/dna-web#19]
Hi,
I am experiencing a similar issue as one of your viewers of a YouTube tutorial, Web Development: 06 Responsive Design, where changes in style.scss is not updating the webpage.  It updates the webpage if I restart WEBDna.  Here is the scenario:  I am running Microsoft Edge on Windows 10 and DNAWeb version 1.0.7.0.  When I make some changes to the .scss file, Sass engine in DNAWeb detects changes in .sccs and generates .css file.  DNAWeb then refreshes the web page, but I don't see the changes on the web page after refresh.  When I view the web page under Developer Tool ->DOM Explorer and Style tabs, the selector for the element shows attribute values (in .css) from when I restarted DNAWeb.  One other thing I notice is when I open the updated .css file, the last attribute for any selector does not end with a semicolon, ';'.  I don't think this is the problem, however.  Any info is appreciated and thank you for all these excellent tutorials on YouTube.

**Comment by Birdey69** [comment]
I had this same issue but i found there was 2 style.css files. 1 in the root directory and 1 in the asset folder that DNAWEB made, i had to make a dna.config file in the root dir to fix it.

**Comment by angelsix** [comment]
If you could provide a zip folder sample and reproduction steps I can take a look

**Comment by Birdey69** [comment]
Luke, i left a zip file in the dropbox i was asking you about on email.
[https://www.dropbox.com/sh/mb17lvdsxcidpp8/AABJw6WsGDFHyvQ-Q2wxpLRoa?dl=0](url)
There is a folder with working and not working.

Basically to fix the issue you need to drop a dna.config file int he sass folder to re-direct the css's to the asset folder and not the root folder.

**Comment by D-code-er** [comment]
Shane,
Thank you for sharing this info.   I will try your suggestion and see if it helps.

As for the steps to re-create the issue.  I am using Microsoft Edge browser and Dnaweb version 1.0.7.0

1. In Window Explorer, go to project folder and type in dnaweb.  for me, the folder is
    "C:\Training\AngelSix\AngelSix_Web\Web_Development_6_Responsive_Web_Design\Responsive"

 2.  Select the above folder and type "dnaweb", hit enter.  In my case, it is an existing project, so Dnaweb starts web page, kicks off  SASS, LiveServer engines, among other engines.   It also brings up Visual Studio code.  At this point the web page is displaying  correctly, meaning, it is using the attribute values set in Assets\css\style.css

 3.  In Visual Studio Code, make some changes to Source\Sass\style.scss, save it.  Dnaweb processes the changed .scss, generates a new .css file and states that it refreshes the web page.  Web page is not updated, however .  I check the Assets\css\style.css and it does have new value from .scss. 

[Responsive.zip](https://github.com/angelsix/dna-web/files/1666144/Responsive.zip)

**Comment by angelsix** [comment]
I've tried the above and it works fine. Can you zip your project and share... or confirm via:

 - Create new folder
 - Type `dnaweb` into address bar
 - type `new template fabric.modern1` into dnaweb
 - Open Edge to show it
 - Edit the scss files in VS Code
 - Watch if Edge refreshes

1. Does it refresh the browser?
2. If it does, does the css update?

I believe the issue is more that the project is setup and outputting the css somewhere else. Look at DnaWeb output it says what file was produced and where

**Comment by D-code-er** [comment]
Hi Luke,
I zipped up my project (not working) and attached in my last response. Please see link "Responsive.zip" above.

I also followed the suggestion from your last response and created a new test project. This time Microsoft Edge successfully updated web page.
What i did was:
1. After created a new project, in Source\Sass\Modern1\_modern1.home.scss, I changed a "h1" element to have text color blue and saved it.   Web page updated header to show "Hello! My name is" in blue. it was previously red color.
2. WebRoot\Assets\Css\modern1.css showed the change for element "h1" from _modern1.home.scss

Attached is the log 
[log.txt](https://github.com/angelsix/dna-web/files/1669636/log.txt)
  from DnaWeb for the change i did.

**Comment by D-code-er** [comment]
Hi Luke,

I installed new Dnaweb 1.0.7.1 and did the following:

  1.
created a new web project using "new template blank",

2. made a change in Sass/style.scss to have background of web page color blue

3. Saved the change in .scss, Dnaweb generated new .css from changed .scss

4. Dnaweb logged web page refresh requested. Web page flickered but it did not changed/Updated.


5. I closed the project.

6. I Created a new folder and created a new web project  using "new template fabric.modern1"

7. I made a change to the h1 element in Sass/Modern1/_modern1.home.scss and saved it

8. Web page updated correctly.


This made me think that the template might has something to do with the web page failed to update in project using "new template blank".


Attached is the folder for "new template blank" project. there is a "log.txt" from Dnaweb in the attached file.








________________________________

**Comment by angelsix** [comment]
The issue is in Edge when editing scss for a page when the html hasnt changed. You edit the html in the modern1 that's why that worked. The issue is fixed in develop I just haven't make a new installer but wrote how to yourself for testing or using it before the next release
