### ISSUE TITLE
[Live server] Css code not updating.

### ISSUE THREAD

**Issue by Hooterr** [angelsix/dna-web#7]
The issue is that when I edit a sass file and hit ctrl+s it updates the output css file but there is no change in browser. It seems like the live server doesn't notice that a css file has been updated. Html code doesn't quite work either. Website doesn't refresh after saving the html file, but after refreshing it manually in browser the changes are visible. 

Short video about the issue: https://www.youtube.com/watch?v=kRPr96K7_0c&feature=youtu.be

**Comment by angelsix** [comment]
Confirmed I am seeing the same thing. You will notice the DnaWeb does detect and process the file fine (your output time changes from :02 to :23 at the end time) however the Web post that should return to inform the browser to refresh seems to get stuck.

I'll investigate and fix for the next release.

**Comment by angelsix** [comment]
Fixed here if you want to just build your own installer for now. I'll release next version over weekend 
https://github.com/angelsix/dna-web/commit/e7b3baf2c203b9b48b4c1ff019ce346139d9ad6b
